// Final Verified Data 2026 - No Gaps, No Syntax Errors
const productData = [
{id:1,cas:"77-73-6",cat:"Additives",en:{name:"Dicyclopentadiene (DCPD)",app:"Epoxy resin modification"},cn:{name:"双环戊二烯 (DCPD)",app:"环氧树脂改性"}},
{id:2,cas:"69-72-7",cat:"Pharma",en:{name:"Salicylic acid",app:"Pharmaceuticals, Dyes"},cn:{name:"水杨酸",app:"医药、日化"}},
{id:3,cas:"/",cat:"Additives",en:{name:"C5 petroleum resin",app:"Adhesives, Road marking"},cn:{name:"C5 石油树脂",app:"胶粘剂、路标漆"}},
{id:4,cas:"/",cat:"Additives",en:{name:"C9 petroleum resin",app:"Inks, Coatings"},cn:{name:"C9 石油树脂",app:"油墨、涂料"}},
{id:5,cas:"119-36-8",cat:"Pharma",en:{name:"Methyl salicylate",app:"Ointments, Personal Care"},cn:{name:"水杨酸甲酯",app:"药油、膏药"}},
{id:6,cas:"54-21-7",cat:"Pharma",en:{name:"Sodium salicylate",app:"Aspirin, Preservatives"},cn:{name:"水杨酸钠",app:"阿司匹林、防腐剂"}},
{id:7,cas:"98-86-2",cat:"Pharma",en:{name:"Acetophenone",app:"Fragrances, Resins"},cn:{name:"苯乙酮",app:"医药、香料"}},
{id:8,cas:"67-68-5",cat:"Solvents",en:{name:"Dimethyl sulfoxide (DMSO)",app:"Chemical synthesis"},cn:{name:"二甲基亚砜 (DMSO)",app:"极性溶剂"}},
{id:9,cas:"122-20-3",cat:"Additives",en:{name:"Triisopropanolamine (TIPA)",app:"Cement grinding aids"},cn:{name:"三异丙醇胺 (TIPA)",app:"水泥助磨剂"}},
{id:10,cas:"6712-98-7",cat:"Additives",en:{name:"Diethanolisopropanolamine (DEIPA)",app:"Cement grinding aids"},cn:{name:"二乙醇单异丙醇胺 (DEIPA)",app:"水泥助磨剂"}},
{id:11,cas:"5343-92-0",cat:"Additives",en:{name:"1,2-Pentanediol (1,2-PDO)",app:"Moisturizers"},cn:{name:"1,2-戊二醇",app:"保湿剂、防腐剂"}},
{id:12,cas:"111-29-5",cat:"Additives",en:{name:"1,5-Pentanediol (1,5-PDO)",app:"Polyester polyols"},cn:{name:"1,5-戊二醇",app:"聚酯多元醇"}},
{id:13,cas:"542-28-9",cat:"Pharma",en:{name:"Delta-Valerolactone",app:"Fine chemicals"},cn:{name:"δ-戊内酯",app:"医药中间体"}},
{id:14,cas:"873-94-9",cat:"Solvents",en:{name:"3,3,5-Trimethylcyclohexanone (TMC)",app:"Coatings"},cn:{name:"3,3,5-三甲基环己酮 (TMC)",app:"高端涂料"}},
{id:15,cas:"75-75-2",cat:"Pharma",en:{name:"Methanesulfonic acid (MSA)",app:"Electroplating"},cn:{name:"甲基磺酸 (MSA)",app:"电镀、医药"}},
{id:16,cas:"38083-17-9",cat:"Pharma",en:{name:"Climbazole",app:"Anti-dandruff"},cn:{name:"氯咪巴唑",app:"去屑洗发水"}},
{id:17,cas:"/",cat:"Additives",en:{name:"Polyether polyols",app:"PU Foams"},cn:{name:"聚醚多元醇",app:"聚氨酯软泡/硬泡"}},
{id:18,cas:"/",cat:"Additives",en:{name:"Polyetheramines (PEA)",app:"Wind power composites"},cn:{name:"聚醚胺 (PEA)",app:"风电固化剂"}},
{id:19,cas:"123-72-8",cat:"Solvents",en:{name:"N-Butyraldehyde",app:"Plasticizers, Coatings"},cn:{name:"正丁醛",app:"增塑剂、涂料"}},
{id:20,cas:"78-84-2",cat:"Solvents",en:{name:"Isobutyraldehyde",app:"Synthesis of NPG"},cn:{name:"异丁醛",app:"合成新戊二醇"}},
{id:21,cas:"110-87-2",cat:"Pharma",en:{name:"3,4-Dihydro-2H-Pyran (DHP)",app:"Hydroxy protective agent"},cn:{name:"3,4-二氢-2H-吡喃 (DHP)",app:"羟基保护剂"}},
{id:22,cas:"2524-04-1",cat:"Agro",en:{name:"O,O-Diethyl Thiophosphoryl Chloride (DETCL)",app:"Agrochemicals"},cn:{name:"O,O-二乙基硫代磷酰氯",app:"有机磷农药中间体"}},
{id:23,cas:"100-51-6",cat:"Solvents",en:{name:"Benzyl alcohol",app:"Coatings, Inks"},cn:{name:"苯甲醇",app:"涂料、油墨"}},
{id:24,cas:"100-52-7",cat:"Fragrance",en:{name:"Benzaldehyde",app:"Fragrances, Pharma"},cn:{name:"苯甲醛",app:"香料、医药中间体"}},
{id:25,cas:"65-85-0",cat:"Additives",en:{name:"Benzoic Acid",app:"Food preservatives"},cn:{name:"苯甲酸",app:"食品防腐剂"}},
{id:26,cas:"100-47-0",cat:"Agro",en:{name:"Benzonitrile",app:"Agrochemical intermediates"},cn:{name:"苯甲腈",app:"农药中间体"}},
{id:27,cas:"98-00-0",cat:"Additives",en:{name:"Furfuryl alcohol",app:"Furan resins"},cn:{name:"糠醇",app:"呋喃树脂"}},
{id:28,cas:"98-01-1",cat:"Additives",en:{name:"Furfural",app:"Casting industry"},cn:{name:"糠醛",app:"加氢制糠醇"}},
{id:29,cas:"97-99-4",cat:"Solvents",en:{name:"Tetrahydrofurfuryl alcohol",app:"Agro solvents"},cn:{name:"四氢糠醇",app:"农药/树脂溶剂"}},
{id:30,cas:"109-99-9",cat:"Solvents",en:{name:"Tetrahydrofuran (THF)",app:"PTMEG, Solvents"},cn:{name:"四氢呋喃 (THF)",app:"PTMEG原料"}},
{id:31,cas:"96-47-9",cat:"Solvents",en:{name:"2-Methyl THF",app:"Green solvents"},cn:{name:"2-甲基四氢呋喃",app:"生物基溶剂"}},
{id:32,cas:"124-41-4",cat:"Additives",en:{name:"Sodium methylate",app:"Biodiesel"},cn:{name:"甲醇钠",app:"生物柴油"}},
{id:33,cas:"865-33-8",cat:"Additives",en:{name:"Potassium methoxide",app:"Organic synthesis"},cn:{name:"甲醇钾",app:"有机合成"}},
{id:34,cas:"141-52-6",cat:"Additives",en:{name:"Sodium ethoxide",app:"Pharma synthesis"},cn:{name:"乙醇钠",app:"医药农药合成"}},
{id:35,cas:"16940-66-2",cat:"Pharma",en:{name:"Sodium borohydride",app:"Bleaching"},cn:{name:"硼氢化钠",app:"纸浆漂白"}},
{id:36,cas:"13762-51-1",cat:"Pharma",en:{name:"Potassium borohydride",app:"Pharmaceuticals"},cn:{name:"硼氢化钾",app:"医药合成"}},
{id:37,cas:"75-65-0",cat:"Solvents",en:{name:"Tert-Butanol",app:"MTBE production"},cn:{name:"叔丁醇",app:"生产MTBE"}},
{id:38,cas:"865-48-5",cat:"Additives",en:{name:"Sodium tert-butoxide",app:"Catalysts"},cn:{name:"叔丁醇钠",app:"有机合成碱催化剂"}},
{id:39,cas:"865-47-4",cat:"Additives",en:{name:"Potassium tert-butoxide",app:"Pharma R&D"},cn:{name:"叔丁醇钾",app:"高端有机合成强碱"}},
{id:40,cas:"1310-58-3",cat:"Additives",en:{name:"Potassium hydroxide (KOH)",app:"Fertilizers"},cn:{name:"氢氧化钾 (KOH)",app:"钾盐制造"}},
{id:41,cas:"584-08-7",cat:"Additives",en:{name:"Potassium carbonate",app:"Glass, Fertilizers"},cn:{name:"碳酸钾",app:"玻璃、化肥"}},
{id:42,cas:"79-09-4",cat:"Additives",en:{name:"Propionic acid",app:"Feed preservatives"},cn:{name:"丙酸",app:"饲料防腐剂"}},
{id:43,cas:"64-19-7",cat:"Solvents",en:{name:"Acetic acid",app:"VAM, PTA"},cn:{name:"乙酸 (冰醋酸)",app:"醋酸乙烯、PTA"}},
{id:44,cas:"96-34-4",cat:"Agro",en:{name:"Methyl chloroacetate",app:"Herbicides"},cn:{name:"氯乙酸甲酯",app:"农药合成"}},
{id:45,cas:"105-39-5",cat:"Agro",en:{name:"Ethyl chloroacetate",app:"Insecticides"},cn:{name:"氯乙酸乙酯",app:"合成除草剂"}},
{id:46,cas:"149-73-5",cat:"Agro",en:{name:"Trimethyl orthoformate",app:"Vitamins"},cn:{name:"原甲酸三甲酯",app:"维生素合成"}},
{id:47,cas:"79-31-2",cat:"Fragrance",en:{name:"Isobutyric acid",app:"Food additives"},cn:{name:"异丁酸",app:"食品添加剂"}},
{id:48,cas:"107-92-6",cat:"Fragrance",en:{name:"Butyric acid",app:"Fragrances"},cn:{name:"正丁酸",app:"香精香料"}},
{id:49,cas:"629-11-8",cat:"Additives",en:{name:"1,6-Hexanediol (HDOL)",app:"Polyurethanes"},cn:{name:"1,6-己二醇 (HDOL)",app:"聚氨酯、聚酯"}},
{id:50,cas:"629-03-8",cat:"Additives",en:{name:"1,6-Dibromohexane (DBH)",app:"Polymer materials"},cn:{name:"1,6-二溴己烷",app:"医药农药中间体"}},
{id:51,cas:"620-19-9",cat:"Pharma",en:{name:"3-Methyl benzyl chloride",app:"Pharmaceuticals"},cn:{name:"3-甲基苄基氯",app:"医药中间体"}},
{id:52,cas:"103694-68-4",cat:"Fragrance",en:{name:"Majantol",app:"Citrus-Floral notes"},cn:{name:"甲基壬乙醛 (Majantol)",app:"香精香料"}},
{id:53,cas:"29823-21-0",cat:"Pharma",en:{name:"Ethyl 8-bromooctanoate",app:"Pharmaceuticals"},cn:{name:"8-溴辛酸乙酯",app:"医药中间体"}},
{id:54,cas:"4707-47-5",cat:"Fragrance",en:{name:"Methyl atratate (Oakmoss)",app:"Perfumes"},cn:{name:"苔黑酚甲醚 (橡苔)",app:"高档香水香料"}},
{id:55,cas:"91-10-1",cat:"Additives",en:{name:"2,6-dimethylphenol (DMP)",app:"PPO/PPE synthesis"},cn:{name:"2,6-二甲基苯酚",app:"聚苯醚 (PPO) 合成"}},
{id:56,cas:"558-30-5",cat:"Pharma",en:{name:"Isobutylene oxide (IBO)",app:"Pharmaceutical synthesis"},cn:{name:"异丁烯环氧化物",app:"医药合成"}},
{id:57,cas:"107-18-6",cat:"Additives",en:{name:"Allyl alcohol",app:"Glycerol production"},cn:{name:"烯丙醇",app:"甘油、烯丙基树脂"}},
{id:58,cas:"67674-46-8",cat:"Fragrance",en:{name:"Methyl Pamplemousse",app:"Grapefruit note"},cn:{name:"圆柚甲烷",app:"高档日化香精"}},
{id:59,cas:"134-20-3",cat:"Fragrance",en:{name:"Methyl 2-aminobenzoate",app:"Pharmaceuticals"},cn:{name:"邻氨基苯甲酸甲酯",app:"香料、医药中间体"}},
{id:60,cas:"67634-15-5",cat:"Fragrance",en:{name:"Floralozone",app:"Floral notes"},cn:{name:"对叔丁基二氢肉桂醛",app:"高档日化香精"}},
{id:61,cas:"118-71-8",cat:"Additives",en:{name:"Maltol",app:"Food additives"},cn:{name:"麦芽酚",app:"食品饮料添加剂"}},
{id:62,cas:"4940-11-8",cat:"Additives",en:{name:"Ethyl Maltol",app:"Flavor enhancers"},cn:{name:"乙基麦芽酚",app:"增香剂"}},
{id:63,cas:"28940-11-6",cat:"Fragrance",en:{name:"Watermelon ketone",app:"Daily chemicals"},cn:{name:"西瓜酮",app:"香水、日化"}},
{id:64,cas:"1222-05-5",cat:"Fragrance",en:{name:"Galaxolide",app:"Personal care"},cn:{name:"佳乐麝香",app:"香水、个人护理品"}},
{id:65,cas:"57-55-6",cat:"Solvents",en:{name:"Propylene glycol (PG)",app:"UPR Resins"},cn:{name:"丙二醇 (PG)",app:"不饱和树脂"}},
{id:66,cas:"25265-71-8",cat:"Solvents",en:{name:"Dipropylene glycol (DPG)",app:"Fragrance carriers"},cn:{name:"二丙二醇 (DPG)",app:"日化、香精载体"}},
{id:67,cas:"108-32-7",cat:"Solvents",en:{name:"Propylene Carbonate (PC)",app:"Battery electrolytes"},cn:{name:"碳酸丙烯酯 (PC)",app:"锂电电解液"}},
{id:68,cas:"7664-38-2",cat:"Additives",en:{name:"Phosphoric acid",app:"Metal treatment"},cn:{name:"磷酸",app:"化肥、食品工业"}},
{id:69,cas:"77-92-9",cat:"Additives",en:{name:"Citric acid",app:"Pharma, Detergents"},cn:{name:"柠檬酸",app:"食品饮料、医药"}},
{id:70,cas:"124-04-9",cat:"Additives",en:{name:"Adipic acid",app:"Nylon 66"},cn:{name:"己二酸",app:"尼龙66、聚氨酯"}},
{id:71,cas:"107-15-3",cat:"Pharma",en:{name:"Ethylenediamine (EDA)",app:"Chelating agents"},cn:{name:"乙二胺 (EDA)",app:"螯合剂、固化剂"}},
{id:72,cas:"10043-35-3",cat:"Additives",en:{name:"Boric acid",app:"Glass, Ceramics"},cn:{name:"硼酸",app:"玻璃、陶瓷"}},
{id:73,cas:"11138-66-2",cat:"Additives",en:{name:"Xanthan gum",app:"Thickeners"},cn:{name:"黄原胶",app:"食品增稠剂"}},
{id:74,cas:"/",cat:"Additives",en:{name:"Monosodium glutamate (MSG)",app:"Seasoning"},cn:{name:"味精 (MSG)",app:"调味品"}},
{id:75,cas:"87-02-5",cat:"Dyes",en:{name:"J acid",app:"Dye intermediates"},cn:{name:"J 酸",app:"染料中间体"}},
{id:76,cas:"90-20-0",cat:"Dyes",en:{name:"H acid",app:"Dye intermediates"},cn:{name:"H 酸",app:"染料中间体"}},
{id:77,cas:"81-16-3",cat:"Dyes",en:{name:"Tobias acid",app:"Azo dyes"},cn:{name:"托拜厄斯酸 (吐氏酸)",app:"偶氮染料中间体"}},
{id:78,cas:"117-62-4",cat:"Dyes",en:{name:"Sulpho tobias acid",app:"Acid dyes"},cn:{name:"磺化吐氏酸",app:"直接和酸性染料"}},
{id:79,cas:"135-19-3",cat:"Dyes",en:{name:"Beta naphthol",app:"Pigments"},cn:{name:"β-萘酚",app:"染料、颜料"}},
{id:80,cas:"121-57-3",cat:"Dyes",en:{name:"Sulphanilic acid",app:"Dye intermediates"},cn:{name:"对氨基苯磺酸",app:"活性染料中间体"}},
{id:81,cas:"482-89-3",cat:"Dyes",en:{name:"Indigo blue",app:"Denim dyeing"},cn:{name:"靛蓝",app:"牛仔布染色"}},
{id:82,cas:"118-03-6",cat:"Dyes",en:{name:"K acid",app:"Agrochemicals"},cn:{name:"K 酸",app:"活性/酸性染料"}},
{id:83,cas:"92-70-6",cat:"Dyes",en:{name:"Bon acid",app:"Organic pigments"},cn:{name:"2,3-酸 (Bon Acid)",app:"染料中间体"}},
{id:84,cas:"612-83-9",cat:"Dyes",en:{name:"DCB",app:"Organic pigments"},cn:{name:"3,3'-二氯联苯胺 (DCB)",app:"有机颜料"}},
{id:85,cas:"59572-10-0",cat:"Additives",en:{name:"PTSA",app:"Acid catalysts"},cn:{name:"对甲苯磺酸 (PTSA)",app:"树脂合成催化剂"}},
{id:86,cas:"62-56-6",cat:"Pharma",en:{name:"Thiourea",app:"Electroplating"},cn:{name:"硫脲",app:"医药、染料、电镀"}},
{id:87,cas:"10079-20-6",cat:"Dyes",en:{name:"Vinyl Sulphone ester",app:"Reactive dyes"},cn:{name:"对位酯 (乙烯砜硫酸酯)",app:"活性染料中间体"}},
{id:88,cas:"486-25-9",cat:"Pharma",en:{name:"9-Fluorenone",app:"Polymer materials"},cn:{name:"9-芴酮",app:"医药、农药、染料"}},
{id:89,cas:"459-57-4",cat:"Pharma",en:{name:"4-Fluorobenzaldehyde",app:"Herbicides"},cn:{name:"4-氟苯甲醛",app:"医药、农药"}},
{id:90,cas:"68-12-2",cat:"Solvents",en:{name:"N,N-DMF",app:"Fiber spinning"},cn:{name:"二甲基甲酰胺 (DMF)",app:"合成革、纤维纺丝"}},
{id:91,cas:"616-38-6",cat:"Solvents",en:{name:"DMC",app:"Battery electrolytes"},cn:{name:"碳酸二甲酯 (DMC)",app:"锂电池电解液"}},
{id:92,cas:"105-58-8",cat:"Solvents",en:{name:"DEC",app:"Organic synthesis"},cn:{name:"碳酸二乙酯 (DEC)",app:"锂电池电解液"}},
{id:93,cas:"68610-51-5",cat:"Additives",en:{name:"Antioxidant",app:"Polymer processing"},cn:{name:"抗氧剂",app:"聚合物加工"}},
{id:94,cas:"9084-06-4",cat:"Dyes",en:{name:"Dispersant MF",app:"Concrete admixtures"},cn:{name:"分散剂 MF",app:"分散染料、混凝土外加剂"}},
{id:95,cas:"36290-04-7",cat:"Dyes",en:{name:"Dispersant NNO",app:"Dyes processing"},cn:{name:"分散剂 NNO",app:"分散染料加工"}},
{id:96,cas:"768-66-1",cat:"Additives",en:{name:"2,2,6,6-HTMP",app:"Light Stabilizers"},cn:{name:"2,2,6,6-四甲基哌啶",app:"光稳定剂中间体"}},
{id:97,cas:"36768-62-4",cat:"Additives",en:{name:"Triacetonediamine (TAD)",app:"HALS production"},cn:{name:"三丙酮胺 (TAD)",app:"光稳定剂生产"}},
{id:98,cas:"42774-15-2",cat:"Additives",en:{name:"SEED",app:"UV Coatings"},cn:{name:"SEED (环氧丙烯酸酯)",app:"UV涂料、3D打印"}},
{id:99,cas:"2226-96-2",cat:"Additives",en:{name:"4-Hydroxy-TEMPO",app:"Inhibitors"},cn:{name:"4-羟基-TEMPO",app:"阻聚剂"}},
{id:100,cas:"52829-07-9",cat:"Additives",en:{name:"HALS 770",app:"Light stabilizers"},cn:{name:"光稳定剂 770",app:"塑料光稳定剂"}},
{id:101,cas:"70198-29-7",cat:"Additives",en:{name:"UV-622",app:"Polyolefins"},cn:{name:"光稳定剂 UV-622",app:"聚烯烃光稳定剂"}},
{id:102,cas:"2403-89-6",cat:"Additives",en:{name:"Pentamethyl-piperidinol",app:"HALS synthesis"},cn:{name:"1,2,2,6,6-五甲基-4-哌啶醇",app:"光稳定剂合成"}},
{id:103,cas:"/",cat:"Additives",en:{name:"Polyether polyol",app:"PU production"},cn:{name:"聚醚多元醇",app:"聚氨酯生产"}},
{id:104,cas:"9046-10-0",cat:"Additives",en:{name:"Polyetheramine (PEA)",app:"Wind power"},cn:{name:"聚醚胺 (PEA)",app:"风电叶片、涂料"}},
{id:105,cas:"85-44-9",cat:"Additives",en:{name:"Phthalic anhydride",app:"Plasticizers"},cn:{name:"苯酐",app:"增塑剂、树脂"}},
{id:106,cas:"108-31-6",cat:"Additives",en:{name:"Maleic anhydride",app:"Water reducers"},cn:{name:"马来酸酐 (顺酐)",app:"不饱和树脂"}},
{id:107,cas:"76-02-8",cat:"Agro",en:{name:"Trichloroacetyl chloride",app:"Agrochemicals"},cn:{name:"三氯乙酰氯",app:"农药、医药中间体"}},
{id:108,cas:"3113-71-1",cat:"Pharma",en:{name:"3-Methyl-4-Nitrobenzoic Acid",app:"APIs"},cn:{name:"3-甲基-4-硝基苯甲酸",app:"原料药"}},
{id:109,cas:"5437-38-7",cat:"Pharma",en:{name:"3-Methyl-2-Nitrobenzoic Acid",app:"APIs"},cn:{name:"3-甲基-2-硝基苯甲酸",app:"原料药"}},
{id:110,cas:"4389-45-1",cat:"Pharma",en:{name:"2-Amino-3-methylbenzoic acid",app:"APIs"},cn:{name:"2-氨基-3-甲基苯甲酸",app:"原料药"}},
{id:111,cas:"20776-67-4",cat:"Pharma",en:{name:"2-Amino-5-chloro-3-methylbenzoic acid",app:"Advanced APIs"},cn:{name:"2-氨基-5-氯-3-甲基苯甲酸",app:"高级原料药"}},
{id:112,cas:"2402-77-9",cat:"Pharma",en:{name:"2,3-Dichloropyridine",app:"Heterocyclic synthesis"},cn:{name:"2,3-二氯吡啶",app:"医药、农药"}},
{id:113,cas:"22841-92-5",cat:"Pharma",en:{name:"3-chloro-2-hydrazylpyridine",app:"APIs"},cn:{name:"3-氯-2-肼基吡啶",app:"原料药"}},
{id:114,cas:"500011-86-9",cat:"Agro",en:{name:"3-Bromo-Pyrazole Acid",app:"Chlorantraniliprole"},cn:{name:"氯虫苯甲酰胺中间体",app:"杀虫剂中间体"}},
{id:115,cas:"105-58-8",cat:"Solvents",en:{name:"Diethyl carbonate",app:"Battery electrolytes"},cn:{name:"碳酸二乙酯",app:"锂电池电解液"}},
{id:116,cas:"76-02-8",cat:"Agro",en:{name:"Trichloroacetyl chloride (TCAC)",app:"Agro/Pharma"},cn:{name:"三氯乙酰氯 (TCAC)",app:"农药中间体"}},
{id:117,cas:"95-57-8",cat:"Agro",en:{name:"Ortho Chloro Phenol (OCP)",app:"Pharmaceuticals"},cn:{name:"邻氯苯酚 (OCP)",app:"农药、医药"}},
{id:118,cas:"77-78-1",cat:"Pharma",en:{name:"Dimethyl sulfate (DMS)",app:"Methylation agents"},cn:{name:"硫酸二甲酯 (DMS)",app:"甲基化剂"}},
{id:119,cas:"108-21-4",cat:"Solvents",en:{name:"Isopropyl Acetate",app:"Inks, Pharma solvents"},cn:{name:"乙酸异丙酯",app:"涂料、医药溶剂"}},
{id:120,cas:"105-46-4",cat:"Solvents",en:{name:"Sec-Butyl acetate",app:"Adhesives"},cn:{name:"乙酸仲丁酯",app:"涂料、胶粘剂"}},
{id:121,cas:"110-54-3",cat:"Solvents",en:{name:"N-Hexane",app:"Oil extraction"},cn:{name:"正己烷",app:"植物油萃取"}},
{id:122,cas:"142-82-5",cat:"Solvents",en:{name:"N-Heptane",app:"Pharma solvents"},cn:{name:"正庚烷",app:"标准试剂"}},
{id:123,cas:"105-46-4",cat:"Solvents",en:{name:"Sec-Butyl acetate",app:"Coatings"},cn:{name:"乙酸仲丁酯",app:"油墨、胶粘剂"}},
{id:124,cas:"68479-98-1",cat:"Additives",en:{name:"DETDA",app:"PU Elastomers"},cn:{name:"二乙基甲苯二胺 (DETDA)",app:"聚氨酯扩链剂"}},
{id:125,cas:"7723-14-0",cat:"Additives",en:{name:"Red phosphorus",app:"Flame retardants"},cn:{name:"红磷",app:"阻燃剂"}},
{id:126,cas:"128-37-0",cat:"Additives",en:{name:"BHT",app:"Antioxidants"},cn:{name:"抗氧剂 BHT",app:"食品/橡胶抗氧剂"}},
{id:127,cas:"35948-25-5",cat:"Additives",en:{name:"DOPO",app:"Flame retardants"},cn:{name:"DOPO",app:"阻燃剂中间体"}},
{id:128,cas:"80-05-7",cat:"Additives",en:{name:"Bisphenol-A",app:"Polycarbonate"},cn:{name:"双酚A",app:"聚碳酸酯、环氧"}},
{id:129,cas:"98-83-9",cat:"Additives",en:{name:"Alpha-methylstyrene",app:"Organic intermediates"},cn:{name:"α-甲基苯乙烯",app:"树脂中间体"}},
{id:130,cas:"120-46-7",cat:"Additives",en:{name:"Dibenzoylmethane (DBM)",app:"PVC stabilizers"},cn:{name:"二苯甲酰甲烷 (DBM)",app:"PVC热稳定剂"}},
{id:131,cas:"58446-52-9",cat:"Additives",en:{name:"SBM",app:"PVC heat stabilizers"},cn:{name:"硬脂酰苯甲酰甲烷 (SBM)",app:"PVC热稳定剂"}},
{id:132,cas:"121-44-8",cat:"Solvents",en:{name:"Triethylamine",app:"Catalysts"},cn:{name:"三乙胺",app:"催化剂"}},
{id:133,cas:"102-71-6",cat:"Additives",en:{name:"Triethanolamine",app:"Cement aids"},cn:{name:"三乙醇胺",app:"表面活性剂"}},
{id:134,cas:"486-25-9",cat:"Pharma",en:{name:"9-Fluorenone",app:"Polymer materials"},cn:{name:"9-芴酮",app:"医药、高分子"}},
{id:135,cas:"112-24-3",cat:"Additives",en:{name:"TETA",app:"Epoxy curing"},cn:{name:"三乙烯四胺",app:"环氧固化剂"}},
{id:136,cas:"111-40-0",cat:"Additives",en:{name:"DETA",app:"Chelating agents"},cn:{name:"二乙烯三胺",app:"环氧固化剂"}},
{id:137,cas:"108-30-5",cat:"Additives",en:{name:"Succinic anhydride",app:"Alkyd resins"},cn:{name:"琥珀酸酐",app:"医药农药中间体"}},
{id:138,cas:"/",cat:"Additives",en:{name:"Epoxy resin",app:"Coatings, Composites"},cn:{name:"环氧树脂",app:"涂料、胶粘剂"}},
{id:139,cas:"61788-89-4",cat:"Additives",en:{name:"Dimer acid",app:"Polyamide resins"},cn:{name:"二聚酸",app:"聚酰胺树脂"}},
{id:140,cas:"142-82-5",cat:"Solvents",en:{name:"n-Heptane",app:"Pharma solvents"},cn:{name:"正庚烷",app:"医药溶剂"}},
{id:141,cas:"110-54-3",cat:"Solvents",en:{name:"Hexane",app:"Oil extraction"},cn:{name:"正己烷",app:"溶剂"}},
{id:142,cas:"760-93-0",cat:"Additives",en:{name:"Methacrylic anhydride",app:"UV curing"},cn:{name:"甲基丙烯酸酐",app:"UV固化树脂"}},
{id:143,cas:"930-68-7",cat:"Pharma",en:{name:"2-Cyclohexen-1-one",app:"Fragrance intermediates"},cn:{name:"2-环己烯-1-酮",app:"医药中间体"}},
{id:144,cas:"67-63-0",cat:"Solvents",en:{name:"Isopropanol (IPA)",app:"Disinfectants"},cn:{name:"异丙醇 (IPA)",app:"电子清洗"}},
{id:145,cas:"123-42-2",cat:"Solvents",en:{name:"Diacetone Alcohol",app:"Coatings"},cn:{name:"双丙酮醇",app:"油墨溶剂"}},
{id:146,cas:"107-21-1",cat:"Solvents",en:{name:"Ethylene glycol (MEG)",app:"Polyester fibers"},cn:{name:"乙二醇 (MEG)",app:"防冻液"}},
{id:147,cas:"111-46-6",cat:"Solvents",en:{name:"Diethylene glycol (DEG)",app:"Plasticizers"},cn:{name:"二甘醇 (DEG)",app:"不饱和树脂"}},
{id:148,cas:"108-94-1",cat:"Solvents",en:{name:"Cyclohexanone",app:"Caprolactam"},cn:{name:"环己酮",app:"溶剂"}},
{id:149,cas:"110-63-4",cat:"Solvents",en:{name:"1,4-butanediol (BDO)",app:"PU production"},cn:{name:"1,4-丁二醇 (BDO)",app:"THF, PU 生产"}},
{id:150,cas:"25190-06-1",cat:"Additives",en:{name:"PTMEG",app:"Spandex fibers"},cn:{name:"聚四氢呋喃 (PTMEG)",app:"PU弹性体"}},
{id:151,cas:"17511-60-3",cat:"Fragrance",en:{name:"Tricyclodecenyl propionate",app:"Woody notes"},cn:{name:"丙酸三环癸烯酯",app:"香精香料"}},
{id:152,cas:"5413-60-5",cat:"Fragrance",en:{name:"Verdyl acetate",app:"Floral notes"},cn:{name:"乙酸苄酯",app:"香精香料"}},
{id:153,cas:"110-05-4",cat:"Additives",en:{name:"DTBP",app:"Crosslinking agents"},cn:{name:"过氧化二叔丁酯 (DTBP)",app:"聚合引发剂"}},
{id:154,cas:"27247-96-7",cat:"Additives",en:{name:"Isooctyl Nitrate",app:"Diesel improvers"},cn:{name:"硝酸异辛酯",app:"柴油改进剂"}},
{id:155,cas:"108-87-2",cat:"Solvents",en:{name:"MCH",app:"Correction fluids"},cn:{name:"甲基环己烷 (MCH)",app:"有机合成"}},
{id:156,cas:"80-46-6",cat:"Additives",en:{name:"PTAP",app:"Phenolic resins"},cn:{name:"对叔戊基苯酚 (PTAP)",app:"橡胶助剂"}},
{id:157,cas:"929-06-6",cat:"Additives",en:{name:"Diglycolamine (DGA)",app:"Desulfurization"},cn:{name:"二甘醇胺 (DGA)",app:"环氧固化剂"}},
{id:158,cas:"75-31-0",cat:"Agro",en:{name:"Isopropylamine (MIPA)",app:"Glyphosate"},cn:{name:"异丙胺 (MIPA)",app:"表面活性剂"}},
{id:159,cas:"1634-04-4",cat:"Additives",en:{name:"MTBE",app:"Octane booster"},cn:{name:"甲基叔丁基醚 (MTBE)",app:"汽油添加剂"}},
{id:160,cas:"57-55-6",cat:"Solvents",en:{name:"MPG",app:"Functional fluids"},cn:{name:"丙二醇 (MPG)",app:"除冰剂"}},
{id:161,cas:"110-98-5",cat:"Solvents",en:{name:"DPG",app:"Fragrance carrier"},cn:{name:"二丙二醇 (DPG)",app:"增塑剂"}},
{id:162,cas:"9003-11-6",cat:"Additives",en:{name:"Poloxamer",app:"Defoamers"},cn:{name:"聚醚嵌段共聚物",app:"消泡剂"}},
{id:163,cas:"2868-37-3",cat:"Agro",en:{name:"Methyl cyclopropanecarboxylate",app:"Agro intermediates"},cn:{name:"环丙烷羧酸甲酯",app:"农药中间体"}},
{id:164,cas:"142-84-7",cat:"Additives",en:{name:"Dipropylamine",app:"Rubber chemicals"},cn:{name:"二正丙胺",app:"农药中间体"}},
{id:165,cas:"78-83-1",cat:"Solvents",en:{name:"Isobutanol",app:"Plasticizers"},cn:{name:"异丁醇",app:"树脂"}},
{id:166,cas:"104-76-7",cat:"Solvents",en:{name:"2-EH",app:"Acrylates"},cn:{name:"异辛醇 (2-EH)",app:"增塑剂"}},
{id:167,cas:"1193-24-4",cat:"Pharma",en:{name:"4,6-Dihydroxypyrimidine",app:"Vitamins"},cn:{name:"4,6-二羟基嘧啶",app:"医药中间体"}},
{id:168,cas:"105-45-3",cat:"Additives",en:{name:"MAA",app:"Organic synthesis"},cn:{name:"乙酰乙酸甲酯",app:"染料"}},
{id:169,cas:"79-11-8",cat:"Additives",en:{name:"Chloroacetic Acid",app:"CMC production"},cn:{name:"氯乙酸",app:"农药"}},
{id:170,cas:"75-15-0",cat:"Additives",en:{name:"Carbon disulfide",app:"Viscose rayon"},cn:{name:"二硫化碳",app:"橡胶助剂"}},
{id:171,cas:"90-02-8",cat:"Fragrance",en:{name:"Salicylaldehyde",app:"Coumarin synthesis"},cn:{name:"水杨醛",app:"农药中间体"}},
{id:172,cas:"123-38-6",cat:"Solvents",en:{name:"Propionaldehyde",app:"Rubber chemicals"},cn:{name:"丙醛",app:"医药中间体"}},
{id:173,cas:"826-36-8",cat:"Additives",en:{name:"TMPO",app:"HALS synthesis"},cn:{name:"四甲基哌啶酮",app:"光稳定剂合成"}},
{id:174,cas:"462-06-6",cat:"Pharma",en:{name:"Fluorobenzene",app:"Agrochemicals"},cn:{name:"氟苯",app:"医药中间体"}},
{id:175,cas:"123-75-1",cat:"Pharma",en:{name:"Pyrrolidine",app:"Organic synthesis"},cn:{name:"吡咯烷",app:"医药中间体"}},
{id:176,cas:"1609-86-5",cat:"Agro",en:{name:"Tert-Butyl Isocyanate",app:"Pharma/Agro synthesis"},cn:{name:"异氰酸叔丁酯",app:"农药中间体"}},
{id:177,cas:"298-12-4",cat:"Pharma",en:{name:"Glyoxylic Acid",app:"Aromas, Pharma"},cn:{name:"乙醛酸",app:"医药中间体"}},
{id:178,cas:"1300-21-6",cat:"Solvents",en:{name:"DCE",app:"Vinyl chloride"},cn:{name:"二氯乙烷 (DCE)",app:"溶剂"}},
{id:179,cas:"75-09-2",cat:"Solvents",en:{name:"DCM",app:"Paint strippers"},cn:{name:"二氯甲烷 (DCM)",app:"清洗剂"}},
{id:180,cas:"63148-62-9",cat:"Additives",en:{name:"Silicone oil",app:"Lubricants"},cn:{name:"硅油",app:"消泡剂"}},
{id:181,cas:"75-18-3",cat:"Solvents",en:{name:"Dimethyl Sulfid (DMS)",app:"Odorants"},cn:{name:"二甲基硫醚 (DMS)",app:"催化剂"}},
{id:182,cas:"9036-19-5",cat:"Additives",en:{name:"OP-10",app:"Surfactants"},cn:{name:"聚氧乙烯辛基苯基醚",app:"乳化剂"}},
{id:183,cas:"100-54-9",cat:"Pharma",en:{name:"3-Cyanopyridine",app:"Vitamin B3"},cn:{name:"3-氰基吡啶",app:"烟酸生产"}},
{id:184,cas:"79-20-9",cat:"Solvents",en:{name:"Methyl Acetate",app:"Inks, Adhesives"},cn:{name:"乙酸甲酯",app:"涂料溶剂"}},
{id:185,cas:"141-78-6",cat:"Solvents",en:{name:"Ethyl Acetate",app:"Extraction"},cn:{name:"乙酸乙酯",app:"稀释剂"}},
{id:186,cas:"109-92-2",cat:"Pharma",en:{name:"Ethyl Vinyl Ether",app:"Fine chemicals"},cn:{name:"乙基乙烯基醚",app:"中间体"}},
{id:187,cas:"64-18-6",cat:"Additives",en:{name:"Formic Acid",app:"Feed preservatives"},cn:{name:"甲酸",app:"皮革鞣制"}},
{id:188,cas:"30525-89-4",cat:"Additives",en:{name:"POM",app:"Engineering plastics"},cn:{name:"聚甲醛 (POM)",app:"工程塑料"}},
{id:189,cas:"13482-23-0",cat:"Pharma",en:{name:"4-Methoxycyclohexanone",app:"APIs"},cn:{name:"4-甲氧基环己酮",app:"医药中间体"}},
{id:190,cas:"/",cat:"Additives",en:{name:"Sucrose Fatty Acid Esters",app:"Emulsifiers"},cn:{name:"蔗糖脂肪酸酯",app:"食品乳化剂"}},
{id:191,cas:"3734-33-6",cat:"Additives",en:{name:"Denatonium Benzoate",app:"Bittering agents"},cn:{name:"苯甲地那铵",app:"苦味剂"}},
{id:192,cas:"71-41-0",cat:"Solvents",en:{name:"n-Pentanol",app:"Fragrances"},cn:{name:"正戊醇",app:"树脂溶剂"}},
{id:193,cas:"107-20-0",cat:"Pharma",en:{name:"Chloroacetaldehyde",app:"Agro synthesis"},cn:{name:"氯乙醛",app:"医药中间体"}},
{id:194,cas:"50-00-0",cat:"Additives",en:{name:"Formaldehyde",app:"Resins"},cn:{name:"甲醛溶液 37%",app:"化工原料"}},
{id:195,cas:"870997-57-2",cat:"Agro",en:{name:"Agro Amide",app:"Insecticides"},cn:{name:"2-氨基-N,3-二甲基苯甲酰胺",app:"农药中间体"}},
{id:196,cas:"32315-10-9",cat:"Pharma",en:{name:"Triphosgene",app:"Organic synthesis"},cn:{name:"三光气",app:"光气替代品"}},
{id:197,cas:"106-48-9",cat:"Agro",en:{name:"P-Chlorophenol (PCP)",app:"Fungicides"},cn:{name:"对氯苯酚 (PCP)",app:"杀菌剂"}},
{id:198,cas:"51-03-6",cat:"Agro",en:{name:"PBO",app:"Insecticide synergist"},cn:{name:"胡椒基丁醚 (PBO)",app:"杀虫剂增效剂"}},
{id:199,cas:"37439-34-2",cat:"Agro",en:{name:"NATCP",app:"Agro intermediates"},cn:{name:"3,5,6-三氯吡啶-2-醇钠",app:"农药中间体"}},
{id:200,cas:"111-76-2",cat:"Solvents",en:{name:"EB",app:"Cleaning agents"},cn:{name:"乙二醇单丁醚",app:"涂料溶剂"}},
{id:201,cas:"75-05-8",cat:"Solvents",en:{name:"Acetonitrile",app:"HPLC solvents"},cn:{name:"乙腈",app:"医药合成"}},
{id:202,cas:"110-86-1",cat:"Solvents",en:{name:"Pyridine",app:"Agro/Pharma"},cn:{name:"吡啶",app:"医药中间体"}},
{id:203,cas:"108-99-6",cat:"Pharma",en:{name:"3-Picoline",app:"Vitamins"},cn:{name:"3-甲基吡啶",app:"农药中间体"}},
{id:204,cas:"616-45-5",cat:"Solvents",en:{name:"2-Pyrrolidinone",app:"Solvents"},cn:{name:"2-吡咯烷酮",app:"中间体"}},
{id:205,cas:"123-62-6",cat:"Pharma",en:{name:"Propionic Anhydride",app:"Flavoring"},cn:{name:"丙酸酐",app:"医药合成"}},
{id:206,cas:"616-47-7",cat:"Additives",en:{name:"1-Methyl imidazole",app:"Catalysts"},cn:{name:"1-甲基咪唑",app:"环氧固化剂"}},
{id:207,cas:"9043-30-5",cat:"Additives",en:{name:"Isotridecyl Alcohol 8 EO",app:"Detergents"},cn:{name:"异三癸醇聚氧乙烯醚",app:"表面活性剂"}},
{id:208,cas:"87-90-1",cat:"Additives",en:{name:"TCCA",app:"Water treatment"},cn:{name:"强氯精 (TCCA)",app:"消毒剂"}},
{id:209,cas:"79-01-6",cat:"Solvents",en:{name:"TCE",app:"Metal degreasing"},cn:{name:"三氯乙烯 (TCE)",app:"溶剂萃取"}},
{id:210,cas:"9016-45-9",cat:"Additives",en:{name:"NPEs",app:"Industrial cleaning"},cn:{name:"壬基酚聚氧乙烯醚 (NPEs)",app:"表面活性剂"}},
{id:211,cas:"26401-47-8",cat:"Additives",en:{name:"Dodecyl Phenol Ethoxylates",app:"Emulsifiers"},cn:{name:"十二烷基酚聚氧乙烯醚",app:"表面活性剂"}},
{id:212,cas:"27603-25-4",cat:"Agro",en:{name:"MSTMT",app:"Agro intermediates"},cn:{name:"2-甲磺酰基-5-三氟甲基-1,3,4-噻二唑",app:"农药中间体"}},
{id:213,cas:"577-11-7",cat:"Additives",en:{name:"Dioctyl sulfosuccinate",app:"Wetting agents"},cn:{name:"琥珀酸二辛酯磺酸钠",app:"润湿剂"}}
];
