// Product Data (Final Combined Version 2026 - Updated with PDF Data)
// Total: 213 Items (Original 174 + 39 from Official List)

const productData = [
{id:1,cas:"77-73-6",cat:"Additives",en:{name:"Dicyclopentadiene (DCPD)",app:"Epoxy resin modification, Chemical intermediates"},cn:{name:"双环戊二烯 (DCPD)",app:"环氧树脂改性，化工中间体"}},
{id:2,cas:"69-72-7",cat:"Pharma",en:{name:"Salicylic acid",app:"Pharmaceuticals, Dyes, Fragrances"},cn:{name:"水杨酸",app:"医药、日化、染料香料合成"}},
{id:3,cas:"/",cat:"Additives",en:{name:"C5 petroleum resin",app:"Adhesives, Road marking paint, Rubber"},cn:{name:"C5 石油树脂",app:"胶粘剂、路标漆、橡胶"}},
{id:4,cas:"/",cat:"Additives",en:{name:"C9 petroleum resin",app:"Printing inks, Coatings, Adhesives"},cn:{name:"C9 石油树脂",app:"油墨、涂料、胶粘剂"}},
{id:5,cas:"119-36-8",cat:"Pharma",en:{name:"Methyl salicylate",app:"Pharmaceuticals, Ointments, Personal Care"},cn:{name:"水杨酸甲酯",app:"药油、膏药、护理品"}},
{id:6,cas:"54-21-7",cat:"Pharma",en:{name:"Sodium salicylate",app:"Pharmaceuticals (Aspirin), Preservatives"},cn:{name:"水杨酸钠",app:"阿司匹林原料、防腐剂"}},
{id:7,cas:"98-86-2",cat:"Pharma",en:{name:"Acetophenone",app:"Pharmaceuticals, Fragrances, Resins"},cn:{name:"苯乙酮",app:"医药、香料、特种树脂"}},
{id:8,cas:"67-68-5",cat:"Solvents",en:{name:"Dimethyl sulfoxide (DMSO)",app:"Solvents, Chemical synthesis"},cn:{name:"二甲基亚砜 (DMSO)",app:"非质子极性溶剂、化工合成"}},
{id:9,cas:"122-20-3",cat:"Additives",en:{name:"Triisopropanolamine (TIPA)",app:"Cement grinding aids, Concrete admixtures"},cn:{name:"三异丙醇胺 (TIPA)",app:"水泥助磨剂、混凝土外加剂"}},
{id:10,cas:"6712-98-7",cat:"Additives",en:{name:"Diethanolisopropanolamine (DEIPA)",app:"Cement grinding aids, Concrete admixtures"},cn:{name:"二乙醇单异丙醇胺 (DEIPA)",app:"水泥助磨剂、混凝土外加剂"}},
{id:11,cas:"5343-92-0",cat:"Additives",en:{name:"1,2-Pentanediol (1,2-PDO)",app:"Moisturizers, Preservatives"},cn:{name:"1,2-戊二醇",app:"保湿剂、防腐剂"}},
{id:12,cas:"111-29-5",cat:"Additives",en:{name:"1,5-Pentanediol (1,5-PDO)",app:"Polyester polyols, Plasticizers"},cn:{name:"1,5-戊二醇",app:"聚酯多元醇、增塑剂"}},
{id:13,cas:"542-28-9",cat:"Pharma",en:{name:"Delta-Valerolactone",app:"Pharmaceutical intermediates, Fine chemicals"},cn:{name:"δ-戊内酯",app:"医药中间体、精细化工"}},
{id:14,cas:"873-94-9",cat:"Solvents",en:{name:"3,3,5-Trimethylcyclohexanone (TMC)",app:"High-end coatings, Peroxide synthesis, Solvents"},cn:{name:"3,3,5-三甲基环己酮 (TMC)",app:"高端涂料、过氧化物合成、溶剂"}},
{id:15,cas:"75-75-2",cat:"Pharma",en:{name:"Methanesulfonic acid (MSA)",app:"Electroplating, Metal treatment, Pharma intermediates"},cn:{name:"甲基磺酸 (MSA)",app:"电镀、金属处理、医药农药中间体"}},
{id:16,cas:"38083-17-9",cat:"Pharma",en:{name:"Climbazole",app:"Anti-dandruff shampoos, Fungicides"},cn:{name:"氯咪巴唑",app:"去屑洗发水、抗真菌剂"}},
{id:17,cas:"/",cat:"Additives",en:{name:"Polyether polyols",app:"PU Foams (Soft/Rigid)"},cn:{name:"聚醚多元醇",app:"聚氨酯软泡/硬泡"}},
{id:18,cas:"/",cat:"Additives",en:{name:"Polyetheramines (PEA)",app:"Epoxy curing agents, Wind power composites"},cn:{name:"聚醚胺 (PEA)",app:"环氧树脂固化剂、风电复合材料"}},
{id:19,cas:"123-72-8",cat:"Solvents",en:{name:"N-Butyraldehyde",app:"Plasticizers, Coatings, Inks, Pharma/Daily chemicals"},cn:{name:"正丁醛",app:"增塑剂、涂料、油墨"}},
{id:20,cas:"78-84-2",cat:"Solvents",en:{name:"Isobutyraldehyde",app:"Synthesis of Neopentyl glycol (NPG)"},cn:{name:"异丁醛",app:"合成新戊二醇 (NPG)"}},
{id:21,cas:"110-87-2",cat:"Pharma",en:{name:"3,4-Dihydro-2H-Pyran (DHP)",app:"Hydroxy protective agent (Pharma/Agro)"},cn:{name:"3,4-二氢-2H-吡喃 (DHP)",app:"羟基保护剂"}},
{id:22,cas:"2524-04-1",cat:"Agro",en:{name:"O,O-Diethyl Thiophosphoryl Chloride (DETCL)",app:"Organophosphorus agrochemical intermediates"},cn:{name:"O,O-二乙基硫代磷酰氯",app:"有机磷农药中间体"}},
{id:23,cas:"100-51-6",cat:"Solvents",en:{name:"Benzyl alcohol",app:"Coatings, Inks, Pharmaceuticals, Fragrances"},cn:{name:"苯甲醇",app:"涂料、油墨、医药、香料"}},
{id:24,cas:"100-52-7",cat:"Fragrance",en:{name:"Benzaldehyde",app:"Fragrances, Pharmaceutical intermediates"},cn:{name:"苯甲醛",app:"香料、医药中间体"}},
{id:25,cas:"65-85-0",cat:"Additives",en:{name:"Benzoic Acid",app:"Food preservatives, Industrial intermediates"},cn:{name:"苯甲酸",app:"食品防腐剂、工业中间体"}},
{id:26,cas:"100-47-0",cat:"Agro",en:{name:"Benzonitrile",app:"Agrochemical intermediates"},cn:{name:"苯甲腈",app:"农药中间体"}},
{id:27,cas:"98-00-0",cat:"Additives",en:{name:"Furfuryl alcohol",app:"Furan resins, Casting materials"},cn:{name:"糠醇",app:"呋喃树脂、铸造材料"}},
{id:28,cas:"98-01-1",cat:"Additives",en:{name:"Furfural",app:"Synthesis of Furfuryl alcohol, Casting industry"},cn:{name:"糠醛",app:"加氢制糠醇、铸造行业"}},
{id:29,cas:"97-99-4",cat:"Solvents",en:{name:"Tetrahydrofurfuryl alcohol",app:"Solvents for Agrochemicals/Resins/Inks, Cleaning agents"},cn:{name:"四氢糠醇",app:"农药/树脂/油墨溶剂、清洗剂"}},
{id:30,cas:"109-99-9",cat:"Solvents",en:{name:"Tetrahydrofuran (THF)",app:"Raw material for PTMEG, Solvents"},cn:{name:"四氢呋喃 (THF)",app:"PTMEG原料、溶剂"}},
{id:31,cas:"96-47-9",cat:"Solvents",en:{name:"2-Methyl THF",app:"Pharma solvents, Bio-based green solvents"},cn:{name:"2-甲基四氢呋喃",app:"医药工艺溶剂、生物基溶剂"}},
{id:32,cas:"124-41-4",cat:"Additives",en:{name:"Sodium methylate",app:"Biodiesel, Organic synthesis"},cn:{name:"甲醇钠",app:"生物柴油、有机合成"}},
{id:33,cas:"865-33-8",cat:"Additives",en:{name:"Potassium methoxide",app:"Organic synthesis"},cn:{name:"甲醇钾",app:"有机合成"}},
{id:34,cas:"141-52-6",cat:"Additives",en:{name:"Sodium ethoxide",app:"Pharmaceutical & Agrochemical synthesis"},cn:{name:"乙醇钠",app:"医药农药合成"}},
{id:35,cas:"16940-66-2",cat:"Pharma",en:{name:"Sodium borohydride",app:"Paper pulp bleaching, Pharma/Agro synthesis"},cn:{name:"硼氢化钠",app:"纸浆漂白、医药/农药合成"}},
{id:36,cas:"13762-51-1",cat:"Pharma",en:{name:"Potassium borohydride",app:"Pharmaceutical synthesis"},cn:{name:"硼氢化钾",app:"医药合成"}},
{id:37,cas:"75-65-0",cat:"Solvents",en:{name:"Tert-Butanol",app:"MTBE/ETBE production, Organic intermediates"},cn:{name:"叔丁醇",app:"生产MTBE/ETBE、有机合成"}},
{id:38,cas:"865-48-5",cat:"Additives",en:{name:"Sodium tert-butoxide",app:"Catalysts for organic synthesis"},cn:{name:"叔丁醇钠",app:"有机合成碱催化剂"}},
{id:39,cas:"865-47-4",cat:"Additives",en:{name:"Potassium tert-butoxide",app:"Strong alkaline catalysts, Pharma/Agro R&D"},cn:{name:"叔丁醇钾",app:"高端有机合成强碱"}},
{id:40,cas:"1310-58-3",cat:"Additives",en:{name:"Potassium hydroxide (KOH)",app:"Potassium salts, Liquid fertilizers, Detergents"},cn:{name:"氢氧化钾 (KOH)",app:"钾盐制造、液体复合肥"}},
{id:41,cas:"584-08-7",cat:"Additives",en:{name:"Potassium carbonate",app:"Glass, Fertilizers, Food additives, Detergents"},cn:{name:"碳酸钾",app:"玻璃、化肥、食品添加剂"}},
{id:42,cas:"79-09-4",cat:"Additives",en:{name:"Propionic acid",app:"Feed preservatives, Agro/Pharma intermediates"},cn:{name:"丙酸",app:"饲料防腐剂、医药农药中间体"}},
{id:43,cas:"64-19-7",cat:"Solvents",en:{name:"Acetic acid",app:"VAM, PTA, Acetates, Acetic anhydride production"},cn:{name:"乙酸 (冰醋酸)",app:"醋酸乙烯、PTA、醋酸酯类"}},
{id:44,cas:"96-34-4",cat:"Agro",en:{name:"Methyl chloroacetate",app:"Agrochemical synthesis (Herbicides, Insecticides)"},cn:{name:"氯乙酸甲酯",app:"农药合成（草甘膦、乐果）"}},
{id:45,cas:"105-39-5",cat:"Agro",en:{name:"Ethyl chloroacetate",app:"Agrochemical synthesis (Herbicides, Insecticides)"},cn:{name:"氯乙酸乙酯",app:"合成除草剂、杀虫剂"}},
{id:46,cas:"149-73-5",cat:"Agro",en:{name:"Trimethyl orthoformate",app:"Vitamins/Pharma synthesis, Agrochemicals"},cn:{name:"原甲酸三甲酯",app:"维生素合成、农药"}},
{id:47,cas:"79-31-2",cat:"Fragrance",en:{name:"Isobutyric acid",app:"Food additives, Fragrances"},cn:{name:"异丁酸",app:"食品添加剂、香料"}},
{id:48,cas:"107-92-6",cat:"Fragrance",en:{name:"Butyric acid",app:"Flavors & Fragrances (Esters)"},cn:{name:"正丁酸",app:"香精香料（酯类合成）"}},
{id:49,cas:"629-11-8",cat:"Additives",en:{name:"1,6-Hexanediol (HDOL)",app:"Polyurethanes, Polyesters, UV/EB curing materials"},cn:{name:"1,6-己二醇 (HDOL)",app:"聚氨酯、聚酯、UV固化材料"}},
{id:50,cas:"629-03-8",cat:"Additives",en:{name:"1,6-Dibromohexane (DBH)",app:"Pharma/Agro intermediates, Polymer materials"},cn:{name:"1,6-二溴己烷",app:"医药农药中间体、高分子材料"}},
{id:51,cas:"620-19-9",cat:"Pharma",en:{name:"3-Methyl benzyl chloride",app:"Pharmaceutical intermediates"},cn:{name:"3-甲基苄基氯",app:"医药中间体"}},
{id:52,cas:"103694-68-4",cat:"Fragrance",en:{name:"Majantol",app:"Fragrances (Citrus-Floral notes)"},cn:{name:"甲基壬乙醛 (Majantol)",app:"香精香料（柑橘花香）"}},
{id:53,cas:"29823-21-0",cat:"Pharma",en:{name:"Ethyl 8-bromooctanoate",app:"Pharmaceutical intermediates"},cn:{name:"8-溴辛酸乙酯",app:"医药中间体"}},
{id:54,cas:"4707-47-5",cat:"Fragrance",en:{name:"Methyl atratate (Oakmoss)",app:"High-end perfumes/fragrances"},cn:{name:"苔黑酚甲醚 (橡苔)",app:"高档香水香料"}},
{id:55,cas:"91-10-1",cat:"Additives",en:{name:"2,6-dimethylphenol (DMP)",app:"Polyphenylene ether (PPO/PPE) synthesis"},cn:{name:"2,6-二甲基苯酚",app:"聚苯醚 (PPO) 合成"}},
{id:56,cas:"558-30-5",cat:"Pharma",en:{name:"Isobutylene oxide (IBO)",app:"Pharmaceutical synthesis"},cn:{name:"异丁烯环氧化物",app:"医药合成（叔丁基）"}},
{id:57,cas:"107-18-6",cat:"Additives",en:{name:"Allyl alcohol",app:"Glycerol production, Allylic resins, Plasticizers"},cn:{name:"烯丙醇",app:"甘油、烯丙基树脂、增塑剂"}},
{id:58,cas:"67674-46-8",cat:"Fragrance",en:{name:"Methyl Pamplemousse",app:"High-end daily fragrances (Grapefruit note)"},cn:{name:"圆柚甲烷",app:"高档日化香精（西柚味）"}},
{id:59,cas:"134-20-3",cat:"Fragrance",en:{name:"Methyl 2-aminobenzoate",app:"Fragrances, Pharmaceutical intermediates"},cn:{name:"邻氨基苯甲酸甲酯",app:"香料、医药中间体"}},
{id:60,cas:"67634-15-5",cat:"Fragrance",en:{name:"Floralozone",app:"High-end daily fragrances (Floral/Ozone note)"},cn:{name:"对叔丁基二氢肉桂醛",app:"高档日化香精（水感花香）"}},
{id:61,cas:"118-71-8",cat:"Additives",en:{name:"Maltol",app:"Food & Beverage additives"},cn:{name:"麦芽酚",app:"食品饮料添加剂"}},
{id:62,cas:"4940-11-8",cat:"Additives",en:{name:"Ethyl Maltol",app:"Flavor enhancers"},cn:{name:"乙基麦芽酚",app:"增香剂"}},
{id:63,cas:"28940-11-6",cat:"Fragrance",en:{name:"Watermelon ketone",app:"Perfumes, Daily chemicals"},cn:{name:"西瓜酮",app:"香水、日化"}},
{id:64,cas:"1222-05-5",cat:"Fragrance",en:{name:"Galaxolide",app:"Perfumes, Personal care products"},cn:{name:"佳乐麝香",app:"香水、个人护理品"}},
{id:65,cas:"57-55-6",cat:"Solvents",en:{name:"Propylene glycol (PG)",app:"UPR Resins, Food & Beverage, Cosmetics, Pharma"},cn:{name:"丙二醇 (PG)",app:"不饱和树脂、食品、化妆品"}},
{id:66,cas:"25265-71-8",cat:"Solvents",en:{name:"Dipropylene glycol (DPG)",app:"Daily chemicals, Fragrance carriers"},cn:{name:"二丙二醇 (DPG)",app:"日化、香精载体"}},
{id:67,cas:"108-32-7",cat:"Solvents",en:{name:"Propylene Carbonate (PC)",app:"Lithium battery electrolytes, Coatings, Adhesives"},cn:{name:"碳酸丙烯酯 (PC)",app:"锂电电解液、涂料、胶粘剂"}},
{id:68,cas:"7664-38-2",cat:"Additives",en:{name:"Phosphoric acid",app:"Fertilizers, Food industry, Metal treatment"},cn:{name:"磷酸",app:"化肥、食品工业、金属处理"}},
{id:69,cas:"77-92-9",cat:"Additives",en:{name:"Citric acid",app:"Food & Beverage, Pharma, Detergents"},cn:{name:"柠檬酸",app:"食品饮料、医药、洗涤剂"}},
{id:70,cas:"124-04-9",cat:"Additives",en:{name:"Adipic acid",app:"Nylon 66, Polyurethanes, Plasticizers"},cn:{name:"己二酸",app:"尼龙66、聚氨酯、增塑剂"}},
{id:71,cas:"107-15-3",cat:"Pharma",en:{name:"Ethylenediamine (EDA)",app:"Chelating agents (EDTA), Epoxy curing, Polyamides"},cn:{name:"乙二胺 (EDA)",app:"螯合剂、固化剂、聚酰胺"}},
{id:72,cas:"10043-35-3",cat:"Additives",en:{name:"Boric acid",app:"Glass, Ceramics, Glazes, Agriculture"},cn:{name:"硼酸",app:"玻璃、陶瓷、釉料、农业"}},
{id:73,cas:"11138-66-2",cat:"Additives",en:{name:"Xanthan gum",app:"Food thickeners, Oil drilling mud"},cn:{name:"黄原胶",app:"食品增稠剂、石油钻井泥浆"}},
{id:74,cas:"/",cat:"Additives",en:{name:"Monosodium glutamate (MSG)",app:"Food seasoning & processing"},cn:{name:"味精 (MSG)",app:"调味品、食品加工"}},
{id:75,cas:"87-02-5",cat:"Dyes",en:{name:"J acid",app:"Dye intermediates (Direct, Reactive, Azo dyes)"},cn:{name:"J 酸",app:"染料中间体（活性、直接染料）"}},
{id:76,cas:"90-20-0",cat:"Dyes",en:{name:"H acid",app:"Dye intermediates (Reactive, Acid, Direct dyes)"},cn:{name:"H 酸",app:"染料中间体（活性、酸性染料）"}},
{id:77,cas:"81-16-3",cat:"Dyes",en:{name:"Tobias acid",app:"Azo dye intermediates"},cn:{name:"托拜厄斯酸 (吐氏酸)",app:"偶氮染料中间体"}},
{id:78,cas:"117-62-4",cat:"Dyes",en:{name:"Sulpho tobias acid",app:"Direct and Acid dye intermediates"},cn:{name:"磺化吐氏酸",app:"直接和酸性染料中间体"}},
{id:79,cas:"135-19-3",cat:"Dyes",en:{name:"Beta naphthol",app:"Dyes, Pigments, Rubber antioxidants, Fragrances"},cn:{name:"β-萘酚",app:"染料、颜料、橡胶防老剂"}},
{id:80,cas:"121-57-3",cat:"Dyes",en:{name:"Sulphanilic acid",app:"Acid/Direct/Reactive dye intermediates"},cn:{name:"对氨基苯磺酸",app:"酸性/直接/活性染料中间体"}},
{id:81,cas:"482-89-3",cat:"Dyes",en:{name:"Indigo blue",app:"Textile dyeing (Denim)"},cn:{name:"靛蓝",app:"牛仔布染色"}},
{id:82,cas:"118-03-6",cat:"Dyes",en:{name:"K acid",app:"Reactive/Acid dye intermediates, Agrochemicals"},cn:{name:"K 酸",app:"活性/酸性染料中间体、农药"}},
{id:83,cas:"92-70-6",cat:"Dyes",en:{name:"Bon acid",app:"Dye intermediates, Organic pigments"},cn:{name:"2,3-酸 (Bon Acid)",app:"染料中间体、有机颜料"}},
{id:84,cas:"612-83-9",cat:"Dyes",en:{name:"DCB",app:"Organic pigments"},cn:{name:"3,3'-二氯联苯胺 (DCB)",app:"有机颜料"}},
{id:85,cas:"59572-10-0",cat:"Additives",en:{name:"PTSA (p-Toluenesulfonic acid)",app:"Acid catalysts for Resins (Phenolic, Melamine)"},cn:{name:"对甲苯磺酸 (PTSA)",app:"树脂合成酸性催化剂"}},
{id:86,cas:"62-56-6",cat:"Pharma",en:{name:"Thiourea",app:"Pharma, Dyes, Electroplating"},cn:{name:"硫脲",app:"医药、染料、电镀"}},
{id:87,cas:"10079-20-6",cat:"Dyes",en:{name:"Vinyl Sulphone ester",app:"Reactive dye intermediates"},cn:{name:"对位酯 (乙烯砜硫酸酯)",app:"活性染料中间体"}},
{id:88,cas:"486-25-9",cat:"Pharma",en:{name:"9-Fluorenone",app:"Pharma, Agro, Dyes, Polymer materials"},cn:{name:"9-芴酮",app:"医药、农药、染料、高分子"}},
{id:89,cas:"459-57-4",cat:"Pharma",en:{name:"4-Fluorobenzaldehyde",app:"Pharmaceuticals, Agrochemicals (Herbicides)"},cn:{name:"4-氟苯甲醛",app:"医药、农药（除草剂）"}},
{id:90,cas:"68-12-2",cat:"Solvents",en:{name:"N,N-Dimethylformamide (DMF)",app:"PU leather solvents, Fiber spinning, Petrochemicals"},cn:{name:"二甲基甲酰胺 (DMF)",app:"合成革浆料、纤维纺丝"}},
{id:91,cas:"616-38-6",cat:"Solvents",en:{name:"Dimethyl carbonate (DMC)",app:"Lithium battery electrolytes, Polycarbonate synthesis"},cn:{name:"碳酸二甲酯 (DMC)",app:"锂电池电解液、聚碳酸酯"}},
{id:92,cas:"105-58-8",cat:"Solvents",en:{name:"Diethyl carbonate (DEC)",app:"Lithium battery electrolytes, Organic synthesis"},cn:{name:"碳酸二乙酯 (DEC)",app:"锂电池电解液、有机合成"}},
{id:93,cas:"68610-51-5",cat:"Additives",en:{name:"Antioxidant",app:"PP/PE Polymer processing"},cn:{name:"抗氧剂",app:"PP/PE 聚合物加工"}},
{id:94,cas:"9084-06-4",cat:"Dyes",en:{name:"Dispersant MF",app:"Disperse dyes, Concrete admixtures"},cn:{name:"分散剂 MF",app:"分散染料、混凝土外加剂"}},
{id:95,cas:"36290-04-7",cat:"Dyes",en:{name:"Dispersant NNO",app:"Disperse dyes processing"},cn:{name:"分散剂 NNO",app:"分散染料加工"}},
{id:96,cas:"768-66-1",cat:"Additives",en:{name:"2,2,6,6-Tetramethylpiperidine (HTMP)",app:"HALS (Light Stabilizers) intermediates"},cn:{name:"2,2,6,6-四甲基哌啶",app:"光稳定剂 (HALS) 中间体"}},
{id:97,cas:"36768-62-4",cat:"Additives",en:{name:"Triacetonediamine (TAD)",app:"HALS (Light Stabilizers) production"},cn:{name:"三丙酮胺 (TAD)",app:"光稳定剂 (HALS) 生产"}},
{id:98,cas:"42774-15-2",cat:"Additives",en:{name:"SEED (Bisphenol A epoxy acrylate)",app:"UV Coatings, Inks, Adhesives, 3D Printing"},cn:{name:"SEED (双酚A环氧丙烯酸酯)",app:"UV涂料、油墨、3D打印"}},
{id:99,cas:"2226-96-2",cat:"Additives",en:{name:"4-Hydroxy-TEMPO",app:"Polymerization inhibitors, Oxidation catalysts"},cn:{name:"4-羟基-TEMPO",app:"阻聚剂、氧化催化剂"}},
{id:100,cas:"52829-07-9",cat:"Additives",en:{name:"HALS 770",app:"Light stabilizers for Plastics/Coatings"},cn:{name:"光稳定剂 770",app:"塑料、涂料光稳定剂"}},
{id:101,cas:"70198-29-7",cat:"Additives",en:{name:"UV-622 (Chimassorb 944)",app:"Light stabilizers for Polyolefins"},cn:{name:"光稳定剂 UV-622",app:"聚烯烃光稳定剂"}},
{id:102,cas:"2403-89-6",cat:"Additives",en:{name:"1,2,2,6,6-Pentamethyl-4-piperidinol",app:"Synthesis of HALS"},cn:{name:"1,2,2,6,6-五甲基-4-哌啶醇",app:"光稳定剂合成"}},
{id:103,cas:"/",cat:"Additives",en:{name:"Polyether polyol",app:"Polyurethane (PU) production"},cn:{name:"聚醚多元醇",app:"聚氨酯 (PU) 生产"}},
{id:104,cas:"9046-10-0",cat:"Additives",en:{name:"Polyetheramine (PEA)",app:"Wind power composites, Coatings, Adhesives"},cn:{name:"聚醚胺 (PEA)",app:"风电叶片、涂料、胶粘剂"}},
{id:105,cas:"85-44-9",cat:"Additives",en:{name:"Phthalic anhydride",app:"Plasticizers, UPR Resins, Dyes"},cn:{name:"苯酐",app:"增塑剂、不饱和树脂、染料"}},
{id:106,cas:"108-31-6",cat:"Additives",en:{name:"Maleic anhydride",app:"UPR Resins, Water reducers, Agrochemicals"},cn:{name:"马来酸酐 (顺酐)",app:"不饱和树脂、减水剂、农药"}},
{id:107,cas:"76-02-8",cat:"Agro",en:{name:"Trichloroacetyl chloride",app:"Agrochemicals, Pharma intermediates"},cn:{name:"三氯乙酰氯",app:"农药、医药中间体"}},
{id:108,cas:"3113-71-1",cat:"Pharma",en:{name:"3-Methyl-4-Nitrobenzoic Acid",app:"APIs, Agrochemicals"},cn:{name:"3-甲基-4-硝基苯甲酸",app:"原料药、农药"}},
{id:109,cas:"5437-38-7",cat:"Pharma",en:{name:"3-Methyl-2-Nitrobenzoic Acid",app:"APIs, Agrochemicals"},cn:{name:"3-甲基-2-硝基苯甲酸",app:"原料药、农药"}},
{id:110,cas:"4389-45-1",cat:"Pharma",en:{name:"2-Amino-3-methylbenzoic acid",app:"APIs, Agrochemicals"},cn:{name:"2-氨基-3-甲基苯甲酸",app:"原料药、农药"}},
{id:111,cas:"20776-67-4",cat:"Pharma",en:{name:"2-Amino-5-chloro-3-methylbenzoic acid",app:"Advanced APIs, Agrochemicals"},cn:{name:"2-氨基-5-氯-3-甲基苯甲酸",app:"高级原料药、农药"}},
{id:112,cas:"2402-77-9",cat:"Pharma",en:{name:"2,3-Dichloropyridine",app:"APIs, Agrochemicals (Heterocyclic synthesis)"},cn:{name:"2,3-二氯吡啶",app:"医药、农药（杂环合成）"}},
{id:113,cas:"22841-92-5",cat:"Pharma",en:{name:"3-chloro-2-hydrazylpyridine",app:"APIs, Agrochemicals"},cn:{name:"3-氯-2-肼基吡啶",app:"原料药、农药"}},
{id:114,cas:"500011-86-9",cat:"Agro",en:{name:"3-Bromo-1-(3-chloro-2-pyridinyl)-1H-pyrazole-5-carboxylic Acid",app:"Insecticide intermediates (Chlorantraniliprole)"},cn:{name:"氯虫苯甲酰胺中间体 (酸)",app:"杀虫剂中间体"}},
{id:115,cas:"105-58-8",cat:"Solvents",en:{name:"Diethyl carbonate",app:"Lithium battery electrolytes, Organic synthesis"},cn:{name:"碳酸二乙酯",app:"锂电池电解液、有机合成"}},
{id:116,cas:"76-02-8",cat:"Agro",en:{name:"Trichloroacetyl chloride (TCAC)",app:"Agrochemicals, Pharma intermediates"},cn:{name:"三氯乙酰氯 (TCAC)",app:"农药、医药中间体"}},
{id:117,cas:"95-57-8",cat:"Agro",en:{name:"Ortho Chloro Phenol (OCP)",app:"Agrochemicals, Pharma, Dyes"},cn:{name:"邻氯苯酚 (OCP)",app:"农药、医药、染料"}},
{id:118,cas:"77-78-1",cat:"Pharma",en:{name:"Dimethyl sulfate (DMS)",app:"Methylation agents (Pharma/Agro/Dyes)"},cn:{name:"硫酸二甲酯 (DMS)",app:"甲基化剂（医药/农药/染料）"}},
{id:119,cas:"108-21-4",cat:"Solvents",en:{name:"Isopropyl Acetate",app:"Coatings, Inks, Pharma solvents"},cn:{name:"乙酸异丙酯",app:"涂料、油墨、医药溶剂"}},
{id:120,cas:"105-46-4",cat:"Solvents",en:{name:"Sec-Butyl acetate",app:"Coatings, Inks, Adhesives"},cn:{name:"乙酸仲丁酯",app:"涂料、油墨、胶粘剂"}},
{id:121,cas:"110-54-3",cat:"Solvents",en:{name:"N-Hexane",app:"Vegetable oil extraction, Solvents"},cn:{name:"正己烷",app:"植物油萃取、溶剂"}},
{id:122,cas:"142-82-5",cat:"Solvents",en:{name:"N-Heptane",app:"Standard reagents, Pharma solvents"},cn:{name:"正庚烷",app:"标准试剂、医药溶剂"}},
{id:123,cas:"105-46-4",cat:"Solvents",en:{name:"Sec-Butyl acetate",app:"Coatings, Inks, Adhesives"},cn:{name:"乙酸仲丁酯",app:"涂料、油墨、胶粘剂"}},
{id:124,cas:"68479-98-1",cat:"Additives",en:{name:"Diethyltoluenediamine (DETDA)",app:"PU Elastomers curing agents, Epoxy hardeners"},cn:{name:"二乙基甲苯二胺 (DETDA)",app:"聚氨酯扩链剂、环氧固化剂"}},
{id:125,cas:"7723-14-0",cat:"Additives",en:{name:"Red phosphorus",app:"Flame retardants, Organic synthesis"},cn:{name:"红磷",app:"阻燃剂、有机合成"}},
{id:126,cas:"128-37-0",cat:"Additives",en:{name:"Butylated hydroxytoluene (BHT)",app:"Antioxidants for Food/Plastics/Rubber"},cn:{name:"抗氧剂 BHT (264)",app:"食品/塑料/橡胶抗氧剂"}},
{id:127,cas:"35948-25-5",cat:"Additives",en:{name:"DOPO",app:"Flame retardant intermediates"},cn:{name:"DOPO",app:"阻燃剂中间体"}},
{id:128,cas:"80-05-7",cat:"Additives",en:{name:"Bisphenol-A",app:"Polycarbonate (PC), Epoxy resins"},cn:{name:"双酚A",app:"聚碳酸酯 (PC)、环氧树脂"}},
{id:129,cas:"98-83-9",cat:"Additives",en:{name:"Alpha-methylstyrene",app:"Resins, Organic intermediates"},cn:{name:"α-甲基苯乙烯",app:"树脂、有机中间体"}},
{id:130,cas:"120-46-7",cat:"Additives",en:{name:"Dibenzoylmethane (DBM)",app:"PVC heat stabilizers, UV absorbers"},cn:{name:"二苯甲酰甲烷 (DBM)",app:"PVC热稳定剂、紫外线吸收剂"}},
{id:131,cas:"58446-52-9",cat:"Additives",en:{name:"Stearoyl benzoyl methane (SBM)",app:"PVC heat stabilizers"},cn:{name:"硬脂酰苯甲酰甲烷 (SBM)",app:"PVC热稳定剂"}},
{id:132,cas:"121-44-8",cat:"Solvents",en:{name:"Triethylamine",app:"Catalysts, Solvents"},cn:{name:"三乙胺",app:"催化剂、溶剂"}},
{id:133,cas:"102-71-6",cat:"Additives",en:{name:"Triethanolamine",app:"Surfactants, Cement grinding aids"},cn:{name:"三乙醇胺",app:"表面活性剂、水泥助磨剂"}},
{id:134,cas:"486-25-9",cat:"Pharma",en:{name:"9-Fluorenone",app:"Pharma, Agro, Dyes, Polymer materials"},cn:{name:"9-芴酮",app:"医药、农药、染料、高分子"}},
{id:135,cas:"112-24-3",cat:"Additives",en:{name:"Triethylenetetramine (TETA)",app:"Epoxy curing agents, Chelating agents"},cn:{name:"三乙烯四胺",app:"环氧固化剂、螯合剂"}},
{id:136,cas:"111-40-0",cat:"Additives",en:{name:"Diethylenetriamine (DETA)",app:"Epoxy curing agents, Chelating agents"},cn:{name:"二乙烯三胺",app:"环氧固化剂、螯合剂"}},
{id:137,cas:"108-30-5",cat:"Additives",en:{name:"Succinic anhydride",app:"Alkyd resins, Pharma/Agro intermediates"},cn:{name:"琥珀酸酐",app:"醇酸树脂、医药农药中间体"}},
{id:138,cas:"/",cat:"Additives",en:{name:"Epoxy resin",app:"Coatings, Composites, Adhesives, Flooring"},cn:{name:"环氧树脂",app:"涂料、复合材料、胶粘剂"}},
{id:139,cas:"61788-89-4",cat:"Additives",en:{name:"Dimer acid",app:"Polyamide resins, Corrosion inhibitors"},cn:{name:"二聚酸",app:"聚酰胺树脂、缓蚀剂"}},
{id:140,cas:"142-82-5",cat:"Solvents",en:{name:"n-Heptane",app:"Standard reagents, Pharma solvents"},cn:{name:"正庚烷",app:"标准试剂、医药溶剂"}},
{id:141,cas:"110-54-3",cat:"Solvents",en:{name:"Hexane",app:"Vegetable oil extraction, Solvents"},cn:{name:"正己烷",app:"植物油萃取、溶剂"}},
{id:142,cas:"760-93-0",cat:"Additives",en:{name:"Methacrylic anhydride",app:"Monomer synthesis, UV curing resins"},cn:{name:"甲基丙烯酸酐",app:"单体合成、UV固化树脂"}},
{id:143,cas:"930-68-7",cat:"Pharma",en:{name:"2-Cyclohexen-1-one",app:"Pharma/Agro/Fragrance intermediates"},cn:{name:"2-环己烯-1-酮",app:"医药/农药/香料中间体"}},
{id:144,cas:"67-63-0",cat:"Solvents",en:{name:"Isopropanol (IPA)",app:"Disinfectants, Solvents, Electronics cleaning"},cn:{name:"异丙醇 (IPA)",app:"消毒剂、溶剂、电子清洗"}},
{id:145,cas:"123-42-2",cat:"Solvents",en:{name:"Diacetone Alcohol",app:"Solvents for Coatings/Inks"},cn:{name:"双丙酮醇",app:"涂料油墨溶剂"}},
{id:146,cas:"107-21-1",cat:"Solvents",en:{name:"Ethylene glycol (MEG)",app:"Polyester fibers, Antifreeze"},cn:{name:"乙二醇 (MEG)",app:"聚酯纤维、防冻液"}},
{id:147,cas:"111-46-6",cat:"Solvents",en:{name:"Diethylene glycol (DEG)",app:"UPR resins, Plasticizers, Dehydration agents"},cn:{name:"二甘醇 (DEG)",app:"不饱和树脂、增塑剂、脱水剂"}},
{id:148,cas:"108-94-1",cat:"Solvents",en:{name:"Cyclohexanone",app:"Caprolactam/Adipic acid production, Solvents"},cn:{name:"环己酮",app:"己内酰胺/己二酸原料、溶剂"}},
{id:149,cas:"110-63-4",cat:"Solvents",en:{name:"1,4-butanediol (BDO)",app:"THF, PBT, GBL, PU production"},cn:{name:"1,4-丁二醇 (BDO)",app:"THF, PBT, GBL, PU 生产"}},
{id:150,cas:"25190-06-1",cat:"Additives",en:{name:"Polytetramethylene Ether Glycol (PTMEG)",app:"Spandex fibers, PU Elastomers"},cn:{name:"聚四氢呋喃 (PTMEG)",app:"氨纶纤维、PU弹性体"}},
{id:151,cas:"17511-60-3",cat:"Fragrance",en:{name:"Tricyclodecenyl propionate",app:"Fragrances (Woody/Amber notes)"},cn:{name:"丙酸三环癸烯酯",app:"香精香料（木香琥珀）"}},
{id:152,cas:"5413-60-5",cat:"Fragrance",en:{name:"Verdyl acetate",app:"Fragrances (Floral/Fruity notes)"},cn:{name:"乙酸苄酯 (Verdyl Acetate)",app:"香精香料（花果香）"}},
{id:153,cas:"110-05-4",cat:"Additives",en:{name:"Di-tert-butyl peroxide (DTBP)",app:"Crosslinking agents, Polymerization initiators"},cn:{name:"过氧化二叔丁酯 (DTBP)",app:"交联剂、聚合引发剂"}},
{id:154,cas:"27247-96-7",cat:"Additives",en:{name:"Isooctyl Nitrate",app:"Diesel Cetane improvers"},cn:{name:"硝酸异辛酯",app:"柴油十六烷值改进剂"}},
{id:155,cas:"108-87-2",cat:"Solvents",en:{name:"Methylcyclohexane (MCH)",app:"Solvents, Organic synthesis, Correction fluids"},cn:{name:"甲基环己烷 (MCH)",app:"溶剂、有机合成、涂改液"}},
{id:156,cas:"80-46-6",cat:"Additives",en:{name:"p-tert-Amylphenol (PTAP)",app:"Phenolic resins, Surfactants, Rubber chemicals"},cn:{name:"对叔戊基苯酚 (PTAP)",app:"酚醛树脂、表面活性剂、橡胶助剂"}},
{id:157,cas:"929-06-6",cat:"Additives",en:{name:"Diglycolamine (DGA)",app:"Desulfurization (Gas treating), Epoxy curing"},cn:{name:"二甘醇胺 (DGA)",app:"脱硫脱碳、环氧固化剂"}},
{id:158,cas:"75-31-0",cat:"Agro",en:{name:"Isopropylamine (MIPA)",app:"Agrochemicals (Glyphosate), Surfactants"},cn:{name:"异丙胺 (MIPA)",app:"农药（草甘膦）、表面活性剂"}},
{id:159,cas:"1634-04-4",cat:"Additives",en:{name:"Methyl tert-butyl ether (MTBE)",app:"Gasoline additive (Octane booster), Solvents"},cn:{name:"甲基叔丁基醚 (MTBE)",app:"汽油添加剂、溶剂"}},
{id:160,cas:"57-55-6",cat:"Solvents",en:{name:"Monopropylene Glycol (MPG)",app:"UPR Resins, Functional fluids, De-icing"},cn:{name:"丙二醇 (MPG)",app:"不饱和树脂、功能流体、除冰剂"}},
{id:161,cas:"110-98-5",cat:"Solvents",en:{name:"Dipropylene glycol (DPG)",app:"Fragrance carrier, UPR resins, Plasticizers"},cn:{name:"二丙二醇 (DPG)",app:"香精载体、树脂、增塑剂"}},
{id:162,cas:"9003-11-6",cat:"Additives",en:{name:"Propoxylated Ethoxylated Block Copolymer",app:"Surfactants, Defoamers, Wetting agents"},cn:{name:"聚醚嵌段共聚物 (Poloxamer)",app:"表面活性剂、消泡剂、润湿剂"}},
{id:163,cas:"2868-37-3",cat:"Agro",en:{name:"Methyl cyclopropanecarboxylate",app:"Agrochemical intermediates"},cn:{name:"环丙烷羧酸甲酯",app:"农药中间体"}},
{id:164,cas:"142-84-7",cat:"Additives",en:{name:"Dipropylamine",app:"Rubber chemicals, Agrochemicals (Trifluralin)"},cn:{name:"二正丙胺",app:"橡胶助剂、农药（氟乐灵）"}},
{id:165,cas:"78-83-1",cat:"Solvents",en:{name:"2-Methyl-1-propanol (Isobutanol)",app:"Solvents, Plasticizers, Resins"},cn:{name:"异丁醇",app:"溶剂、增塑剂、树脂"}},
{id:166,cas:"104-76-7",cat:"Solvents",en:{name:"2-Ethyl-1-hexanol (2-EH)",app:"Plasticizers (DOP), Acrylates, Coatings"},cn:{name:"异辛醇 (2-EH)",app:"增塑剂 (DOP)、丙烯酸酯、涂料"}},
{id:167,cas:"1193-24-4",cat:"Pharma",en:{name:"4,6-Dihydroxypyrimidine",app:"Pharmaceutical intermediates, Vitamins"},cn:{name:"4,6-二羟基嘧啶",app:"医药中间体、维生素B4"}},
{id:168,cas:"105-45-3",cat:"Additives",en:{name:"Methyl Acetoacetate (MAA)",app:"Organic synthesis, Dyes, Agrochemicals"},cn:{name:"乙酰乙酸甲酯",app:"有机合成、染料、农药"}},
{id:169,cas:"79-11-8",cat:"Additives",en:{name:"Chloroacetic Acid",app:"CMC production, Agrochemicals (2,4-D)"},cn:{name:"氯乙酸",app:"CMC生产、农药 (2,4-D)"}},
{id:170,cas:"75-15-0",cat:"Additives",en:{name:"Carbon disulfide",app:"Viscose rayon, Cellophane, Rubber chemicals"},cn:{name:"二硫化碳",app:"粘胶纤维、玻璃纸、橡胶助剂"}},
{id:171,cas:"90-02-8",cat:"Fragrance",en:{name:"Salicylaldehyde",app:"Synthesis of coumarin, Violet fragrances, Pesticides"},cn:{name:"水杨醛",app:"合成香豆素、紫罗兰香料、农药中间体"}},
{id:172,cas:"123-38-6",cat:"Solvents",en:{name:"Propionaldehyde",app:"Pharma intermediates, Plastics, Rubber chemicals"},cn:{name:"丙醛",app:"医药中间体、塑料、橡胶助剂"}},
{id:173,cas:"826-36-8",cat:"Additives",en:{name:"2,2,6,6-Tetramethyl-4-piperidinone",app:"Synthesis of Hindered Amine Light Stabilizers (HALS)"},cn:{name:"四甲基哌啶酮 (TMPO)",app:"受受阻胺光稳定剂 (HALS) 合成"}},
{id:174,cas:"462-06-6",cat:"Pharma",en:{name:"Fluorobenzene",app:"Agrochemicals, Pharma intermediates, Resins"},cn:{name:"氟苯",app:"农药、医药中间体、树脂"}},
{id:175,cas:"123-75-1",cat:"Pharma",en:{name:"Pyrrolidine",app:"Pharmaceutical intermediates, Organic synthesis"},cn:{name:"吡咯烷",app:"医药中间体、有机合成"}},
{id:176,cas:"1609-86-5",cat:"Agro",en:{name:"Tert-Butyl Isocyanate",app:"Synthesis of pharmaceuticals and agrochemicals"},cn:{name:"异氰酸叔丁酯",app:"医药农药合成中间体"}},
{id:177,cas:"298-12-4",cat:"Pharma",en:{name:"Glyoxylic Acid",app:"Aromas, Pharmaceutical intermediates, Personal care"},cn:{name:"乙醛酸",app:"香料、医药中间体、日化原料"}},
{id:178,cas:"1300-21-6",cat:"Solvents",en:{name:"Dichloroethane (DCE)",app:"Solvents, Raw material for Vinyl chloride"},cn:{name:"二氯乙烷 (DCE)",app:"溶剂、氯乙烯原料"}},
{id:179,cas:"75-09-2",cat:"Solvents",en:{name:"Dichloromethane (DCM)",app:"Paint strippers, Cleaning, Chemical processing"},cn:{name:"二氯甲烷 (DCM)",app:"脱漆剂、金属清洗、化工工艺"}},
{id:180,cas:"63148-62-9",cat:"Additives",en:{name:"Silicone oil",app:"Lubricants, Hydraulic fluids, Defoamers"},cn:{name:"硅油",app:"润滑剂、液压油、消泡剂"}},
{id:181,cas:"75-18-3",cat:"Solvents",en:{name:"Dimethyl Sulfid (DMS)",app:"Solvents, Catalysts, Odorants"},cn:{name:"二甲基硫醚 (DMS)",app:"溶剂、催化剂、赋臭剂"}},
{id:182,cas:"9036-19-5",cat:"Additives",en:{name:"Polyoxyethylene octylphenyl ether",app:"Non-ionic surfactants, Detergents"},cn:{name:"聚氧乙烯辛基苯基醚",app:"非离子表面活性剂、洗涤剂"}},
{id:183,cas:"100-54-9",cat:"Pharma",en:{name:"3-Cyanopyridine",app:"Niacin (Vitamin B3) production, Agrochemicals"},cn:{name:"3-氰基吡啶",app:"烟酸 (VB3) 生产、农药"}},
{id:184,cas:"79-20-9",cat:"Solvents",en:{name:"Methyl Acetate",app:"Solvents for paints, inks, and adhesives"},cn:{name:"乙酸甲酯",app:"涂料、油墨、胶粘剂溶剂"}},
{id:185,cas:"141-78-6",cat:"Solvents",en:{name:"Ethyl Acetate",app:"Solvents for coatings, extraction, thinners"},cn:{name:"乙酸乙酯",app:"涂料、萃取、稀释剂"}},
{id:186,cas:"109-92-2",cat:"Pharma",en:{name:"Ethyl Vinyl Ether",app:"Intermediates for fine chemicals and flavors"},cn:{name:"乙基乙烯基醚",app:"精细化工、香精香料中间体"}},
{id:187,cas:"64-18-6",cat:"Additives",en:{name:"Formic Acid",app:"Leather tanning, Feed preservatives, Intermediates"},cn:{name:"甲酸",app:"皮革鞣制、饲料防腐、化工中间体"}},
{id:188,cas:"30525-89-4",cat:"Additives",en:{name:"Polyoxymethylene (POM)",app:"Engineering plastics, Automotive parts"},cn:{name:"聚甲醛 (POM)",app:"工程塑料、汽车配件"}},
{id:189,cas:"13482-23-0",cat:"Pharma",en:{name:"4-Methoxycyclohexanone",app:"Pharmaceutical intermediates"},cn:{name:"4-甲氧基环己酮",app:"医药中间体"}},
{id:190,cas:"/",cat:"Additives",en:{name:"Sucrose Fatty Acid Esters",app:"Food emulsifiers, Personal care products"},cn:{name:"蔗糖脂肪酸酯",app:"食品乳化剂、个人护理品"}},
{id:191,cas:"3734-33-6",cat:"Additives",en:{name:"Denatonium Benzoate",app:"Alcohol denaturants, Bittering agents"},cn:{name:"苯甲地那铵",app:"酒精变性剂、苦味剂"}},
{id:192,cas:"71-41-0",cat:"Solvents",en:{name:"n-Pentanol",app:"Fragrances, Solvents for resins/oils"},cn:{name:"正戊醇",app:"香料、树脂油类溶剂"}},
{id:193,cas:"107-20-0",cat:"Pharma",en:{name:"Chloroacetaldehyde",app:"Pharmaceutical and Agrochemical synthesis"},cn:{name:"氯乙醛",app:"医药农药中间体"}},
{id:194,cas:"50-00-0",cat:"Additives",en:{name:"Formaldehyde 37% solution",app:"Resins (PF/MF), Chemical production"},cn:{name:"甲醛溶液 37%",app:"树脂制造、化工原料"}},
{id:195,cas:"870997-57-2",cat:"Agro",en:{name:"2-amino-N,3-dimethylbenzamide",app:"Agrochemical intermediates (Insecticides)"},cn:{name:"2-氨基-N,3-二甲基苯甲酰胺",app:"农药中间体（杀虫剂）"}},
{id:196,cas:"32315-10-9",cat:"Pharma",en:{name:"Triphosgene",app:"Phosgene replacement, Organic synthesis"},cn:{name:"三光气",app:"光气替代品、有机合成"}},
{id:197,cas:"106-48-9",cat:"Agro",en:{name:"P-Chlorophenol (PCP)",app:"Fungicides, Dyes, Chemical intermediates"},cn:{name:"对氯苯酚 (PCP)",app:"杀菌剂、染料中间体"}},
{id:198,cas:"51-03-6",cat:"Agro",en:{name:"Piperonyl Butoxide (PBO)",app:"Synergist for insecticides"},cn:{name:"胡椒基丁醚 (PBO)",app:"杀虫剂增效剂"}},
{id:199,cas:"37439-34-2",cat:"Agro",en:{name:"3,5,6-Trichloropyridin-2-ol sodium (NATCP)",app:"Agrochemical intermediates"},cn:{name:"3,5,6-三氯吡啶-2-醇钠 (NATCP)",app:"农药中间体"}},
{id:200,cas:"111-76-2",cat:"Solvents",en:{name:"Ethylene Glycol Monobutyl Ether",app:"Cleaning agents, Coatings, Solvents"},cn:{name:"乙二醇单丁醚",app:"清洗剂、涂料溶剂"}},
{id:201,cas:"75-05-8",cat:"Solvents",en:{name:"Acetonitrile",app:"HPLC solvents, Pharmaceutical synthesis"},cn:{name:"乙腈",app:"HPLC溶剂、医药合成"}},
{id:202,cas:"110-86-1",cat:"Solvents",en:{name:"Pyridine",app:"Solvents, Agro/Pharma intermediates"},cn:{name:"吡啶",app:"溶剂、医药农药中间体"}},
{id:203,cas:"108-99-6",cat:"Pharma",en:{name:"3-Picoline",app:"Vitamins, Agrochemical intermediates"},cn:{name:"3-甲基吡啶",app:"维生素、农药中间体"}},
{id:204,cas:"616-45-5",cat:"Solvents",en:{name:"2-Pyrrolidinone (2-p)",app:"Solvents, Polymer intermediates"},cn:{name:"2-吡咯烷酮",app:"溶剂、聚合物中间体"}},
{id:205,cas:"123-62-6",cat:"Pharma",en:{name:"Propionic Anhydride",app:"Pharmaceutical synthesis, Flavoring agents"},cn:{name:"丙酸酐",app:"医药合成、赋味剂"}},
{id:206,cas:"616-47-7",cat:"Additives",en:{name:"1-Methyl imidazole",app:"Catalysts, Epoxy curing agents"},cn:{name:"1-甲基咪唑",app:"催化剂、环氧固化剂"}},
{id:207,cas:"9043-30-5",cat:"Additives",en:{name:"Isotridecyl Alcohol 8 EO",app:"Surfactants, Detergents"},cn:{name:"异三癸醇聚氧乙烯醚",app:"表面活性剂、洗涤剂"}},
{id:208,cas:"87-90-1",cat:"Additives",en:{name:"Trichloroisocyanuric Acid (TCCA)",app:"Disinfectants, Water treatment, Bleaching"},cn:{name:"强氯精 (TCCA)",app:"消毒剂、水处理、漂白"}},
{id:209,cas:"79-01-6",cat:"Solvents",en:{name:"Trichloroethylene (TCE)",app:"Metal degreasing, Solvent extraction"},cn:{name:"三氯乙烯 (TCE)",app:"金属脱脂、溶剂萃取"}},
{id:210,cas:"9016-45-9",cat:"Additives",en:{name:"Nonylphenol Ethoxylates (NPEs)",app:"Non-ionic surfactants, Industrial cleaning"},cn:{name:"壬基酚聚氧乙烯醚 (NPEs)",app:"非离子表面活性剂、工业清洗"}},
{id:211,cas:"26401-47-8",cat:"Additives",en:{name:"Dodecyl Phenol Ethoxylates",app:"Surfactants, Emulsifiers"},cn:{name:"十二烷基酚聚氧乙烯醚",app:"表面活性剂、乳化剂"}},
{id:212,cas:"27603-25-4",cat:"Agro",en:{name:"MSTMT",app:"Agrochemical intermediates"},cn:{name:"2-甲磺酰基-5-三氟甲基-1,3,4-噻二唑",app:"农药中间体"}},
{id:213,cas:"577-11-7",cat:"Additives",en:{name:"Dioctyl sulfosuccinate sodium salt",app:"Wetting agents, Surfactants"},cn:{name:"琥珀酸二辛酯磺酸钠",app:"润湿剂、表面活性剂"}}
];
